name: projectgabung
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.1
  salomon_bottom_bar: ^3.3.2
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.9
  share_plus: ^7.0.2
  flutter_typeahead: ^4.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
